Repository aws/aws-sdk-go, pull requests merged in 2020-03, with the labels that each got.

#3181 `service`: modifies custom integration test to be examples
  service/iotdataplane/cust_integration_test.go
  service/iotdataplane/endpoint_example_test.go
  service/mediastoredata/cust_integration_test.go
  service/mediastoredata/endpoint_example_test.go
Labels: needs-review

#3188 `service`: Fix for bug in SDKs endpoint discovery
  private/model/api/codegentest/service/awsendpointdiscoverytest/api.go
  private/model/api/codegentest/service/awsendpointdiscoverytest/endpoint_discovery_test.go
  private/model/api/operation.go
  service/dynamodb/api.go
Labels: pr/ready-to-merge

#3183 Improve memory allocation behavior by replacing sync.Pool with custom pool implementation
  CHANGELOG_PENDING.md
  service/s3/s3manager/pool.go
  service/s3/s3manager/pool_test.go
  service/s3/s3manager/upload.go
  service/s3/s3manager/upload_internal_test.go
Labels: pr/needs-review

#3194 aws/session: Support Shared Config Role Duration Config Option
  aws/session/credentials.go
  aws/session/credentials_test.go
  aws/session/shared_config.go
  aws/session/testdata/shared_config
Labels: pr/needs-review
